### ISSUE TITLE
[REFACTOR] ProfileScreen 구조 개선 및 컴포넌트화

### ISSUE THREAD

**Issue by seohyun09** [su-yeong-ice-pork/front-end#13]
## 🛠️ Description 
`gluestack-ui`를 이용하여 기존 `ProfileScreen.tsx`를 컴포넌트화 한다.

## ✅ TODO
- [x] 프로필 헤더
- [x] 현재 나의 잔디 친구/스터디그룹 목록 박스
- [x] 개인 잔디 정보
- [x] 비밀번호 변경하기/로그아웃 버튼

## 💻 etc.
보유 뱃지와 보유 프리즈 컴포넌트는 `HomeScreen`에서 구조화된 컴포넌트를 이후에 재사용할 예정이다.
