### ISSUE TITLE
[REFACTOR] StudyScreen 구조 변경 및 개선

### ISSUE THREAD

**Issue by KIMJINWOO4** [su-yeong-ice-pork/front-end#20]
## 🛠️ Description 

StudyScreen 구조 변경 및 개선을 진행한다.

## ✅ TODO
- [x] 기본 컴포넌트를 gluestack ui로 변경
- [x] 컴포넌트를 단위 별로 분리하여 관리
- [x] 스타일/타입/상수 분리하여 관리

## 💻 etc.

데이터 로직은 추후 모든 컴포넌트 디자인 패턴 리팩토링이 완료된 후 진행할 예정
