### ISSUE TITLE
[REFACTOR] SignUpScreen 구조 개선 및 컴포넌트화

### ISSUE THREAD

**Issue by seohyun09** [su-yeong-ice-pork/front-end#28]
## 🛠 Description 
`gluestack-ui`를 이용하여 기존 `SignUpScreen.tsx`를 컴포넌트화 한다.

## ✅ TODO
- [x] 회원가입 헤더(타이틀)
- [x] 학교 이메일 인증 박스
- [x] 학과 등록
- [x] 비밀번호 입력
- [x] 이름(닉네임) 입력
- [x] 잔디 심으러 가기 버튼
