### ISSUE TITLE
[REFACTOR] 캘린더 구조 개선 및 컴포넌트화

### ISSUE THREAD

**Issue by taeyomi** [su-yeong-ice-pork/front-end#29]
## 🛠️ Description 
- 월간 캘린더 및 연간 캘린더 컴포넌트화
- 공부 기록 컴포넌트화

## ✅ TODO

- [ ]  기본 컴포넌트를 gluestack ui로 변경
- [ ]  컴포넌트를 단위 별로 분리하여 관리
- [ ]  스타일/타입/상수 분리하여 관리
