### ISSUE TITLE
[REFACTOR] AlarmScreen 리팩토링

### ISSUE THREAD

**Issue by KIMJINWOO4** [su-yeong-ice-pork/front-end#32]
## 🛠️ Description 

알람 스크린을 조건에 맞춰 리팩토링 진행할 예정입니다.

## ✅ TODO

- [x] 기본 컴포넌트를 gluestack ui로 변경
- [x] 컴포넌트를 단위 별로 분리하여 관리
- [x] 스타일/타입/상수 분리하여 관리
