### ISSUE TITLE
[REFACTOR] StudyRecordScreen 구조 개선

### ISSUE THREAD

**Issue by KIMJINWOO4** [su-yeong-ice-pork/front-end#35]
## 🛠️ Description 

StudyRecordScreen에 대해 구조 개선을 진행하겠습니다.

## ✅ TODO

- [x] 기본 컴포넌트를 gluestack ui로 변경
- [x] 컴포넌트를 단위 별로 분리하여 관리
- [x] 스타일/타입/상수 분리하여 관리
